server {
	listen 80;
	listen [::]:80;
	server_name theboah.tech www.theboah.tech;

	location /.well-known/acme-challenge/ {
		root /var/www/certbot;
	}

	location / {
		return 301 https://theboah.tech$request_uri;
	}
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name theboah.tech www.theboah.tech;

	ssl_certificate /etc/letsencrypt/live/theboah.tech/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/theboah.tech/privkey.pem;
	add_header Permissions-Policy "geolocation=(self)" always;

	location /api/ {
		proxy_pass http://host.docker.internal:3500;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	location / {
		proxy_pass http://host.docker.internal:5713;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
