domain name is theboah.tech
host locally at 3500 for api 
so theboah.tech/api will be proxied to localhost:3500/api

host fronend at 3000 for react app
so anything else goes to theboah.tech:3000

Figure out cert stuff
